name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar snake customizada
        uses: Platane/snk@v3
        with:
          github_user_name: LisJustino
          outputs: |
            dist/github-snake-elisa.svg?color_snake=8e44ad&color_dots=#f5eef8,#d2b4de,#a569bd,#8e44ad
            dist/github-snake-elisa-dark.svg?palette=github-dark&color_snake=8e44ad

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
